version: '3'

services:
  server:
    image: revenz/fileflows
    restart: unless-stopped
    ports:
      - "19200:5000"
    environment:
      - TempPathHost=${APP_DATA_DIR}/temp
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/temp:/temp
      - ${APP_DATA_DIR}/data:/app/Data
      - ${APP_DATA_DIR}/logs:/app/Logs
      - ${APP_DATA_DIR}/common:/app/common
      - ${UMBREL_ROOT}/data/storage/downloads/:downloads:rw

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: brunov-tests-fileflows_server_1
      APP_PORT: 19200
      restart: unless-stopped
