version: '3'

services:
  server:
    image: revenz/fileflows
    restart: unless-stopped
    ports:
      - "19200:5000"
    environment:
      - TempPathHost=${APP_DATA_DIR}/temp
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/temp:/temp
      - ${APP_DATA_DIR}/data:/app/Data
      - ${APP_DATA_DIR}/logs:/app/Logs
      - ${APP_DATA_DIR}/common:/app/common
      - ${UMBREL_ROOT}/data/storage/downloads/:downloads:rw
