version: '3'

services:
  server:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - :4545
    volumes:
      - ${UMBREL_ROOT}/data/storage/apps-config:/data/config
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: brunov-homepage_server_1
      APP_PORT: 4545:4545
      restart: unless-stopped
