version: '3.7'

services:
  server:
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/config:/app/config
      - ${APP_DATA_DIR}/assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 4848:8080
    labels:
      glance.hide: true
